name: rateit
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.4+3
  firebase_database: ^3.1.3
  firebase_auth: ^0.16.0
  google_maps_flutter: ^0.5.26
  path_provider: ^1.6.7
  screenshots: ^2.1.1
  provider: ^4.0.5
  cloud_firestore: ^0.13.5
  flutter_spinkit: "^4.1.2"
  material_design_icons_flutter: ^2.3.50
  email_validator: '^1.0.0'
  #barcode_scan: ^2.0.2
  image_picker: ^0.6.5+3
  cupertino_icons: ^0.1.2
  flutter_google_places: ^0.2.4
  geocoder: ^0.2.1
  flutter_rating_bar: ^3.0.1+1
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0
  geopoint: ^0.7.1
  rating_bar: ^0.2.0
  json_serializable: ^3.3.0
  random_string: ^2.0.1
  firebase_storage: ^3.1.0+1
  auto_size_text: ^2.1.0
  shared_preferences: ^0.5.7
  dropdownfield: ^1.0.0
  location: ^3.0.2
  barcode: ^1.9.1
  pdf: ^1.7.1
  barcode_image: ^1.0.2
  barcode_widget: ^1.2.3
  file_utils: ^0.1.4
  permission_handler: ^5.0.0+hotfix.5




  # qr_utils: ^0.1.4
  # mailer: ^3.0.4


  # cached_network_image: "^0.4.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

  splashscreen: ^1.2.0
  open_file: ^3.0.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - asset/image/Chat.png
   - asset/image/facebook.png
   - asset/image/google.png
   - asset/image/arrow.png
   - asset/image/icon.png
   - asset/image/check.png
   - asset/image/envelope.png
   - asset/images/
   - asset/image/location.png
   - asset/image/upload.png
   - asset/image/caffeparha.png
   - asset/image/carbie.png
   - asset/image/kfc.png
   - asset/image/doh.png
   - asset/image/noliesfries.png
   - asset/image/meetthecheese.png
   - asset/image/thestory.png
   - asset/image/cloudnaan.png
   - asset/image/mcdonalds.png
   - asset/image/menu.png
   - asset/image/bin.png
   - asset/image/search.png
   - asset/image/user.png
   - asset/image/
   - asset/image/rateit.png
   - asset/image/McFries.png
   - asset/image/bigmac.png
   - asset/image/mcchicken.png
   - asset/image/Group 55.png
   - asset/image/uzair_1.jpeg
   - asset/image/uzair_2.jpeg
   - asset/image/avatar.png
   - asset/image/avatar1.png
   
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
fonts: 
    - family: Copse
      fonts:
      - asset: asset/fonts/Copse-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages